baseurl = "//pierreca.github.io/"
languageCode = "en-us"
title = "Making, Flying and Diving"
copyright = "(c) 2016 Pierre Cauchois"
metaDataFormat = "yaml"
theme = "hyde-y"

[params]
    brand = "Making, Flying and Diving"
    topline = "Pierre Cauchois"
    sidebar = "left"
    github = "pierreca"
    twitter = "pierreca"
    linkedin = "pierrecauchois"
