baseurl = "//pierreca.github.io/"
languageCode = "en-us"
title = "So much to learn!"
copyright = "(c) 2023 Pierre Cauchois"
metaDataFormat = "yaml"
theme = ["hyde-hyde", "hugo-shortcode-gallery"]
postNavigation = false

[params]
    brand = "So much to learn!"
    topline = "Pierre Cauchois"
    sidebar = "left"
    themeColor = "theme-base-0d"
    layoutReverse = true

[params.social]
    github = "pierreca"
    linkedin = "pierrecauchois"

[menu]
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
  [[menu.main]]
    identifier = "aviation"
    name = "Aviation"
    url = "/aviation"
  [[menu.main]]
    identifier = "reads"
    name = "Bookshelf"
    url = "/bookshelf"
  [[menu.main]]
    identifier = "podcasts"
    name = "Podcasts"
    url = "/podcasts"
  [[menu.main]]
    identifier = "diving"
    name = "Diving"
    url = "/diving"
  [[menu.main]]
    identifier = "woodworking"
    name = "Woodworking"
    url = "/woodworking"
